/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "simp.h"

results *
readfile_1(argp, rqstp)
	opnds *argp;
	struct svc_req *rqstp;
{

	static results  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
