/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SIMP_H_RPCGEN
#define _SIMP_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAXSIZE 512

struct opnds {
	char *fileName;
	int startLine;
	int endLine;
};
typedef struct opnds opnds;
#ifdef __cplusplus
extern "C" bool_t xdr_opnds(XDR *, opnds*);
#elif __STDC__
extern  bool_t xdr_opnds(XDR *, opnds*);
#else /* Old Style C */
bool_t xdr_opnds();
#endif /* Old Style C */


#ifdef __cplusplus
extern "C" bool_t xdr_opnds(XDR *, opnds*);
#elif __STDC__
extern  bool_t xdr_opnds(XDR *, opnds*);
#else /* Old Style C */
bool_t xdr_opnds();
#endif /* Old Style C */

#define MAXBUF 512

struct results {
	int status;
	union {
		char recvVal[MAXBUF];
		int reason;
	} results_u;
};
typedef struct results results;
#ifdef __cplusplus
extern "C" bool_t xdr_results(XDR *, results*);
#elif __STDC__
extern  bool_t xdr_results(XDR *, results*);
#else /* Old Style C */
bool_t xdr_results();
#endif /* Old Style C */


#define SIMP_PROG ((rpc_uint)0x33897645)
#define SIMP_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define READFILE ((rpc_uint)1)
extern "C" results * readfile_1(opnds *, CLIENT *);
extern "C" results * readfile_1_svc(opnds *, struct svc_req *);

#elif __STDC__
#define READFILE ((rpc_uint)1)
extern  results * readfile_1(opnds *, CLIENT *);
extern  results * readfile_1_svc(opnds *, struct svc_req *);

#else /* Old Style C */
#define READFILE ((rpc_uint)1)
extern  results * readfile_1();
extern  results * readfile_1_svc();
#endif /* Old Style C */

#endif /* !_SIMP_H_RPCGEN */
