/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "simp.h"


void
simp_prog_1(host, fileName, startLine, endLine)
char *host;
char* fileName;
int startLine;
int endLine;
{
	CLIENT *clnt;
	results  *result_1;
	opnds  readfile_1_arg;
	clnt = clnt_create(host, SIMP_PROG, SIMP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	result_1 = readfile_1(&readfile_1_arg, clnt );
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}



main(argc, argv)
int argc;
char *argv[];
{
	char *host;

	if(argc < 5) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	char *fileName = argv[2];
	int startLine = argv[3];
	int endLine = argv[4]; 
	simp_prog_1( host, fileName, startLine, endLine);
}