/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "simp.h"

results *
readfile_1_svc(opnds *argp, struct svc_req *rqstp)
{
	static results  result;
	int startLine = argp->startLine;
	int endLine = argp->endLine;
//	printf("These are the lines of code %d %d",startLine,endLine);
	//char filename[] = opnds->fileName;
	FILE *file = fopen(argp->fileName, "rb");
	
	int count = 0;
	char buff[1000000];
	if( file != NULL )
	{	//printf("I am here where are you");
	    char line[256]; /* or other suitable maximum line size */
	    while (startLine <= endLine && fgets(line, sizeof(line), file) != NULL) /* read a line */
	    {   
	        if (count >= startLine && count <= endLine)
	        {  
			//printf("Line read by server  is %s\n",line); 
	        	result.status=0;
			strcat(buff,line);
	        }
		//printf("I am reading file");
	        count++;
	    
	    }   
	    	fclose(file);
		result.results_u.recvVal = buff;
		//printf("Line is %s\n",result.results_u.recvVal);
	}
	else
	{
	    printf("File does not exist");
	    //file doesn't exist
	/*
	 * insert server code here
	 */
	}
	return &result;
}
