/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SIMP_H_RPCGEN
#define _SIMP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSIZE 512

struct opnds {
	char *fileName;
	int startLine;
	int endLine;
};
typedef struct opnds opnds;

#define MAXBUF 512

struct results {
	int status;
	union {
		char *recvVal;
		int reason;
	} results_u;
};
typedef struct results results;

#define SIMP_PROG 0x33897645
#define SIMP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define READFILE 1
extern  results * readfile_1(opnds *, CLIENT *);
extern  results * readfile_1_svc(opnds *, struct svc_req *);
extern int simp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READFILE 1
extern  results * readfile_1();
extern  results * readfile_1_svc();
extern int simp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_opnds (XDR *, opnds*);
extern  bool_t xdr_opnds (XDR *, opnds*);
extern  bool_t xdr_results (XDR *, results*);

#else /* K&R C */
extern bool_t xdr_opnds ();
extern bool_t xdr_opnds ();
extern bool_t xdr_results ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SIMP_H_RPCGEN */
