/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "simp.h"

results *
readfile_1_svc(opnds *argp, struct svc_req *rqstp)
{
	static results  result;
	int startLine = argp->startLine;
	int endLine = argp->endLine;
	printf("These are the lines of code %d %d",startLine,endLine);
	//char filename[] = opnds->fileName;
	FILE *file = fopen(argp->fileName, "rb");
	
	int count = 0;
	if( file != NULL )
	{	printf("I am here where are you");
	    char line[256]; /* or other suitable maximum line size */
	    while (fgets(line, sizeof(line), file) != NULL) /* read a line */
	    {   
	        if (count == startLine)
	        {  
			printf("Line read by server  is %s\n",line); 
	        	result.status=0;
			strcat(result.results_u.recvVal,line);
	        }
		printf("I am reading file");
	        count++;
	    
	    }   
	    fclose(file);
	}
	else
	{
	    printf("Not exist");
	    //file doesn't exist
	/*
	 * insert server code here
	 */
	}
	return &result;
}
